Store.PresentationLayer/Areas/Administration/Controllers/AdminProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Store.BusinessLogicLayer.Models.Users;
using Store.BusinessLogicLayer.Serviсes.Interfaces;
using System.Threading.Tasks;
using Store.Sharing.Constants;

namespace Store.PresentationLayer.Areas.Administration.Controllers
{
    [Area("Administration")]
    public class AdminProfileController : Controller
    {
        private readonly IUserService _userService;

        public AdminProfileController(IUserService userService)
        {
            _userService = userService;
        }//TODO add new line
        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> GetProfile()
        {
            var accessToken = HttpContext.Request.Cookies[Constants.AreaConstants.JWT];
            var result = await _userService.GetUserByIdAsync(accessToken);
            return View(Constants.AreaConstants.VIEW_PROFILE, result);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateProfile()
        {
            var accessToken = HttpContext.Request.Cookies[Constants.AreaConstants.JWT];
            var result = await _userService.GetUserByIdAsync(accessToken);
            return View(Constants.AreaConstants.VIEW_PROFILE_UPDATE, result);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateProfile(UserUpdateModel updateModel)
        {
            var accessToken = HttpContext.Request.Cookies[Constants.AreaConstants.JWT];
            await _userService.UserUpdateAsync(updateModel, accessToken);
            return RedirectToAction(Constants.AreaConstants.ACTION_GETPROFILE);
        }


        [HttpGet]
        public IActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> ChangePassword(ChangePasswordModel changePasswordModel)
        {
            if (ModelState.IsValid)
            {
                var accessToken = HttpContext.Request.Cookies[Constants.AreaConstants.JWT];
                await _userService.ChangePasswordAsync(changePasswordModel, accessToken);
                return RedirectToAction(Constants.AreaConstants.ACTION_SIGN_IN, Constants.AreaConstants.CONTROLLER_ADMIN_ACCount);
            }
            return View();
        }
    }
}

Store.PresentationLayer/Areas/Administration/Views/AdminProfile/ChangePassword.cshtml
@model Store.BusinessLogicLayer.Models.Users.ChangePasswordModel

@{
    Layout = "~/_Layout.cshtml";
}

@{
    <div class="mainContent">
        <h2>Change password</h2>
        <form id="changepasswordForm" class="stardart-font" asp-controller="AdminProfile" asp-action="ChangePassword">
            <div class="form-group">
                <label class="control-label">Current password </label>
                <input name="currentPassword" type="text" asp-for="CurrentPassword" class="form-control stardart-font" /><br />
                <span class="field-validation-error" id="currentPasswordError"></span>
            </div>
            <div class="form-group">
                <label class="control-label">New password</label>
                <input name="newPassword" type="text" asp-for="NewPassword" class="form-control stardart-font" /><br />
                <span class="field-validation-error" id="newPasswordError"></span>
            </div>

            <div class="form-group">
                <label class="control-label">Confirm password</label>
                <input name="confirmPassword" type="text" class="form-control stardart-font" /><br />
                <span class="field-validation-error" id="passwordMatchingError"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save changes" class="btn btn-default button" onClick="return checkform();" />
                <input class="button" type="button" value="Cancel" onclick="location.href='@Url.Action("GetProfile", "AdminProfile")'" />
            </div>
        </form>
    </div>
}

@section scripts{
    <script>
        function checkform() {//TODO camelCase pls
            var form = document.getElementById('changepasswordForm');//TODO camelCase pls
            var result = true;

            var exp = new RegExp(new String("((?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@@#$%_!%&*]).{8,20})"));

            document.getElementById("currentPasswordError").innerHTML = "";
            document.getElementById("newPasswordError").innerHTML = "";
            document.getElementById("newPasswordError").innerHTML = "";

            if (form.currentPassword.value == "") {
                document.getElementById("currentPasswordError").innerHTML = "Current password requared";//TODO spelling
                result = false;
            }

            if (form.newPassword.value == "") {
                document.getElementById("newPasswordError").innerHTML = "New password requared";//TODO spelling
                result = false;
            }

            if (form.newPassword.value != "" && !exp.test(form.newPassword.value)) {
                document.getElementById("newPasswordError").innerHTML =
                    "Min password length 8, One ore more lowercase characters, One ore more uppercase characters, Any symbols \"@@#$%_!%&* \", One more digit from 0-9";
                result = false;
            }

            if (form.newPassword.value != form.confirmPassword.value) {
                document.getElementById("passwordMatchingError").innerHTML = "Passwords must be the same";
                result = false;
            }
            return result;
        }</script>
}

Store.PresentationLayer/Areas/Administration/Views/AdminProfile/Profile.cshtml
@model Store.BusinessLogicLayer.Models.Users.UserModel
@{
    Layout = "~/_Layout.cshtml";
}
@{
    <div class="mainContent">
    <h2>Profile:</h2>
        <a>Last Name:</a>
        <a class="from-query">@Model.LastName</a><br>

        <a>First Name:</a>
        <a class="from-query">@Model.FirstName</a><br>

        <a>Email:</a>
        <a class="from-query">@Model.Email</a><br>
    <input class="button" type="button" value="Update profile" onclick="location.href='@Url.Action("UpdateProfile", "AdminProfile")'" />
    </div>
}

Store.PresentationLayer/Areas/Administration/Views/AdminProfile/ProfileUpdate.cshtml
@model Store.BusinessLogicLayer.Models.Users.UserModel

@{
    Layout = "~/_Layout.cshtml";
}

@{
    <div class="mainContent">
        <h2>Update profile</h2>
        <form class="stardart-font" asp-controller="AdminProfile" asp-action="UpdateProfile">
            <div class="form-group">
                <label asp-for="Id " class="control-label">ID</label>
                <input type="text" disabled="disabled" asp-for="Id" class="form-control stardart-font from-query" />
            </div>
            <div class="form-group">
                <label asp-for="LastName " class="control-label">Last name</label>
                <input type="text" asp-for="LastName" class="form-control stardart-font from-query" />
            </div>
            <div class="form-group">
                <label asp-for="FirstName " class="control-label">First name</label>
                <input type="text" asp-for="FirstName" class="form-control stardart-font from-query" />
            </div>

            <div class="form-group">
                <label asp-for="Email " class="control-label">Email</label>
                <input type="email" asp-for="Email" class="form-control stardart-font from-query" />
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default button" />
                <input class="button" type="button" value="Cancel" onclick="location.href='@Url.Action("GetProfile", "AdminProfile")'" />
                <input class="button" type="button" value="Change password" onclick="location.href='@Url.Action("ChangePassword", "AdminProfile")'" />
            </div>
        </form>
    </div>
}