Store.PresentationLayer/Areas/Administration/Controllers/AuthorsManagementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Store.BusinessLogicLayer.Models.Authors;
using Store.BusinessLogicLayer.Serviсes.Interfaces;
using Store.Sharing.Constants;
//TODO extra line
using System.Threading.Tasks;

namespace Store.PresentationLayer.Areas.Administration.Controllers
{
    [Area("Administration")]
    public class AuthorsManagementController : Controller
    {
        private readonly IAuthorService _authorService;
        public AuthorsManagementController(IAuthorService authorService)
        {
            _authorService = authorService;
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> GetAuthors(string sortBy = Constants.AreaConstants.AUTHOR_DEF_SORT_PARAMS, bool isAsc = true, int page = Constants.AreaConstants.FIRST_PAGE)
        {
            var sortModel = new AuthorFiltrationModel
            {
                Name = HttpContext.Request.Cookies[Constants.AreaConstants.AUTHOR_NAME_COOKIES],
                PropertyForSort = sortBy,
                IsAscending = isAsc,
                CurrentPage = page,
            };
            var result = await _authorService.GetAsync(sortModel);

            return View(Constants.AreaConstants.VIEW_AUTHORS, result);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> GetAuthorProfile(long id)
        {
            var result = await _authorService.GetByIdAsync(id);

            return View(Constants.AreaConstants.VIEW_AUTHOR_PROFILE, result);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateAuthor(AuthorModel updateModel)
        {
            await _authorService.UpdateAsync(updateModel);
            var query = HttpContext.Request.Headers[Constants.AreaConstants.PATH].ToString();//TODO spelling+++
            return Redirect(query); 
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult AddNewAuthor()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> AddNewAuthor(AuthorModel model)
        {
            await _authorService.CreateAsync(model);
            return View("AddNewAuthor");
        }
    }
}

Store.PresentationLayer/Areas/Administration/Controllers/EditionManagementController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Store.BusinessLogicLayer.AdminServices.Interfeces;//TODO unused directive
using Store.BusinessLogicLayer.Models.EditionModel;
using Store.BusinessLogicLayer.Serviсes.Interfaces;
using Store.Sharing.Constants;
using System.Collections.Generic;
using System.Threading.Tasks;
using static Store.DataAccessLayer.Enums.Enums;

namespace Store.PresentationLayer.Areas.Administration.Controllers
{
    [Area("Administration")]
    public class EditionManagementController : Controller
    {

        private readonly IPrintingEditionService _editionService;
        private readonly IPrintingEditionServiceAdmin _editionServiceAdmin;//TODO missing directive
        private readonly IAuthorService _authorService;

        public EditionManagementController(IPrintingEditionService editionService, IAuthorService authorService, IMapper mapper, IPrintingEditionServiceAdmin editionServiceAdmin)//TODO missing directive
        {
            _editionService = editionService;
            _authorService = authorService;
            _editionServiceAdmin = editionServiceAdmin;
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> GetEditions(string sortBy = Constants.AreaConstants.EDITION_DEF_SORT_PARAMS, bool isAsc = true, int page = Constants.AreaConstants.FIRST_PAGE)//TODO edition_DEF_sort_params. what def mean?
        {
            var sortModel = new EditionFiltrationModel
            {
                Title = HttpContext.Request.Cookies[Constants.AreaConstants.EDITION_TITLE_COOKIES],
                PropertyForSort = sortBy,
                IsAscending = isAsc,
                CurrentPage = page,
                EditionType = new List<PrintingEditionType>() { PrintingEditionType.Book, PrintingEditionType.Magazine, PrintingEditionType.Newspaper }//TODO would be better create .ctor with default set by edition type. Check this pls
            };
            var result = await _editionService.GetAsync(sortModel);

            return View(Constants.AreaConstants.VIEW_EDITIONS, result);

        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> GetEditions(EditionFiltrationModel model)
        {
            var result = await _editionService.GetAsync(model);
            return View(Constants.AreaConstants.VIEW_EDITIONS, result);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> GetEditionProfile(long id)
        {
            var editionModel = await _editionService.GetByIdAsync(id);
            return View(Constants.AreaConstants.VIEW_EDITION_PROFILE, editionModel);

        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> AddNewEdition()
        {
            var allAuthorsModels = await _authorService.GetAllAsync();
            var createModel = new EditionCreateViewModel() { AllAuthorModels = allAuthorsModels };
            return View(createModel);

        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> AddNewEdition(EditionCreateViewModel model)
        {
            await _editionServiceAdmin.CreateEditionByAdminAsync(model);
            return Ok($"{model.Title} {Constants.AreaConstants.EDITION_CREATE_MSG}");  
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateEdition(long id)
        {
            var editionModel = await _editionService.GetByIdAsync(id);
            var allAuthorsModels = await _authorService.GetAllAsync();
            var updateViewModel = new EditionUpdateViewModel() { PrintingEdition = editionModel, AllAuthorModels = allAuthorsModels };
            return View(Constants.AreaConstants.VIEW_UPDATE_EDITION, updateViewModel);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateEdition(EditionUpdateViewModel model)
        {
            await _editionServiceAdmin.UpdateEditionByAdminAsync(model);
            return View(Constants.AreaConstants.VIEW_EDITION_PROFILE, await _editionService.GetByIdAsync(model.PrintingEdition.Id));
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteEdition(long id, string url)
        {
            await _editionService.RemoveAsync(id);
            return Redirect(url);
        }
    }
}

Store.PresentationLayer/Areas/Administration/Views/EditionManagement/AddNewEdition.cshtml
@model Store.BusinessLogicLayer.Models.EditionModel.EditionCreateViewModel
@{
    Layout = "~/_Layout.cshtml";
}

@section AddToHead
{
    <link href="~/Styles/ManagementStyleSheet.css" rel="stylesheet" type="text/css" />
}
@{
    <div class=mainContent>
        <h2>Add new edition</h2>
        <form class="stardart-font" asp-controller="EditionManagement" asp-action="AddNewEdition">
            <div class="form-group">
                <label asp-for="Title" class="control-label">Title</label>
                <input type="text" asp-for="Title" />
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Description</label>
                <input type="text" asp-for="Description" />
            </div>
            <div class="form-group">
                <label asp-for="EditionType" class="control-label">Edition Type</label>
                <select style="font-size: 16px" asp-for="EditionType" asp-items="Html.GetEnumSelectList<Store.DataAccessLayer.Enums.Enums.PrintingEditionType>()"></select>

            </div>
            <div class="form-group">
                <label asp-for="AuthorsNames" class="control-label">Authors</label>
                <input id="authorsAdded" type="text" asp-for="AuthorsNames"/>
                <select style="font-size: 16px" id="authorFromList">
                    @foreach (Store.BusinessLogicLayer.Models.Authors.AuthorModel author in Model.AllAuthorModels)//TODO redundant
                    {
                        <option value="@author.Name">@author.Name</option>
                    }
                </select>
                <input type="button" value="Add author" class="btn btn-default button" onclick="addAuthor()" />
            </div>
            <div class="form-group">
                <label asp-for="Currency" class="control-label">Currency</label>
                <select style="font-size: 16px" asp-for="Currency" asp-items="Html.GetEnumSelectList<Store.DataAccessLayer.Enums.Enums.CurrencyType>()"></select>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label">Price</label>
                <input type="text" asp-for="Price" />
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label">Status</label>
                <select style="font-size: 16px" asp-for="Status">
                    <option selected="selected" value="Available">Available</option>
                    <option value="Unavailable">Unavailable</option>
                </select>
            </div>
            <input type="submit" value="Add" class="btn btn-default button" />
        </form>
    </div>
}
@section scripts{
    <script>
        function addAuthor() {
            var authors = document.getElementById("authorsAdded").value + "";
            if (authors === "") {
                document.getElementById("authorsAdded").value = document.getElementById("authorFromList").value;
                document.getElementById("authorsAdded").focus();
                
                return;
            }

            var authorFromList = document.getElementById("authorFromList").value + "";

            if (!authors.includes(authorFromList)) {
                document.getElementById("authorsAdded").value = authors + ", " + authorFromList;
                document.getElementById("authorsAdded").focus();
            }
        }
        //TODO extra line
    </script>
}

Store.PresentationLayer/Areas/Administration/Views/EditionManagement/EditionProfile.cshtml
@model Store.BusinessLogicLayer.Models.EditionModel.PrintingEditionModel
@{
    Layout = "~/_Layout.cshtml";
}

@section AddToHead
{
    <link href="~/Styles/ManagementStyleSheet.css" rel="stylesheet" type="text/css" />
}
@{
    <div class=mainContent>
        <h2>Edition profile:</h2>  
        <form class="stardart-font" asp-controller="EditionsManagement" asp-action="UpdateEdition"> /*TODO check controller*/ 
            <div class="form-group">
                <label asp-for="Id " class="control-label">ID</label>
                <input type="text" disabled="disabled" value="@Model.Id" class="form-control stardart-font from-query" />
                <input type="text" hidden="hidden" asp-for="Id" />
            </div>

            <div class="form-group">
                <label asp-for="DateOfCreation" class="control-label">Created at: </label>
                <input type="text" disabled="disabled" asp-for="DateOfCreation" class="form-control stardart-font from-query" />
            </div>

            <div class="form-group">
                <label asp-for="Title" class="control-label">Title</label>
                <input type="text" disabled="disabled" asp-for="Title" class="form-control stardart-font from-query" />
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label">Discription</label>
                <input type="text" disabled="disabled" asp-for="Description" class="form-control stardart-font from-query" />
            </div>

            <div class="form-group">
                <label asp-for="Status" class="control-label">Status</label>
                <input type="text" disabled="disabled" asp-for="Status" class="form-control stardart-font from-query" />
            </div>

            <div class="form-group">
                <label asp-for="EditionType" class="control-label">Type</label>
                <input type="text" disabled="disabled" asp-for="EditionType" class="form-control stardart-font from-query" />
            </div>

            <div class="form-group">
                <label asp-for="Currency" class="control-label">Currency</label>
                <input type="text" disabled="disabled" asp-for="Currency" class="form-control stardart-font from-query" />
            </div>

            <div class="form-group">
                <label asp-for="Price" class="control-label">Price</label>
                <input type="text" disabled="disabled" asp-for="Price" class="form-control stardart-font from-query" />
            </div>

            <a>Authors:</a>
            <select style="font-size: 16px" id="author">

                @foreach (Store.BusinessLogicLayer.Models.Authors.AuthorModel author in Model.AuthorModels) //TODO redundant
                {
                    <option value="@author.Id" class="from-query">@author.Name</option>
                }
            </select>
            <input class="button" type="button" value="Open author profile" onclick="goToAuthorProfile();" /><br>
            <input type="button" value="Update" class="btn btn-default button" onclick="update(@Model.Id);" />
        </form>
    </div>
}
@section scripts{
    <script>
        function goToAuthorProfile()
        {
            var id = document.getElementById("author").value;
            return window.location.href = '@Url.Action("GetAuthorProfile", "AuthorsManagement")?Id=' + id;
        }

        function update(id) {
            return window.location.href = '@Url.Action("UpdateEdition", "EditionManagement")?id=' + id;
        }
    </script>
}

Store.PresentationLayer/Areas/Administration/Views/EditionManagement/Editions.cshtml
@model Store.BusinessLogicLayer.Models.PaginationsModels.NavigationModelBase<Store.BusinessLogicLayer.Models.EditionModel.PrintingEditionModel>
@{
    Layout = "~/_Layout.cshtml";
}

@section AddToHead
{
    <link href="~/Styles/ManagementStyleSheet.css" rel="stylesheet" type="text/css" />
}
@{


    <form class="stardart-font" asp-controller="AuthorsManagement" asp-action="GetAuthors">
        <table>
            <tr>
                <th>
                    Id
                    <span class="sort-button">
                        <input type="button" value="1-9" class="btn btn-default button" onclick="sort(`Id`,`asc`);" />
                        <input type="button" value="9-1" class="btn btn-default button" onclick="sort(`Id`,`dsc`);" />
                    </span>
                </th>
                <th>
                    Title
                    <span class="sort-button">
                        <input type="button" value="a-z" class="btn btn-default button" onclick="sort(`Title`,`asc`);" />
                        <input type="button" value="z-a" class="btn btn-default button" onclick="sort(`Title`,`dsc`);" />
                    </span>
                </th>
                <th>
                   Authors
                </th>
                <th>
                    Price
                    <span class="sort-button">
                        <input type="button" value="a-z" class="btn btn-default button" onclick="sort(`Price`,`asc`);" />
                        <input type="button" value="z-a" class="btn btn-default button" onclick="sort(`Price`,`dsc`);" />
                    </span>
                </th>
                <th>
                    Currency
                    <span class="sort-button">
                        <input type="button" value="a-z" class="btn btn-default button" onclick="sort(`Currency`,`asc`);" />
                        <input type="button" value="z-a" class="btn btn-default button" onclick="sort(`Currency`,`dsc`);" />
                    </span>
                </th>
                <th>
                    Status
                    <span class="sort-button">
                        <input type="button" value="a-z" class="btn btn-default button" onclick="sort(`Status`,`asc`);" />
                        <input type="button" value="z-a" class="btn btn-default button" onclick="sort(`Status`,`dsc`);" />
                    </span>
                </th>
                <th>Actions</th>
            </tr>
            @foreach (Store.BusinessLogicLayer.Models.EditionModel.PrintingEditionModel edition in Model.Models) //TODO redundant
            {
        <tr>
            <td>@edition.Id</td>
            <td>@edition.Title</td>
            <td>
                <select style="font-size: 16px" id="edition">

                    @foreach (Store.BusinessLogicLayer.Models.Authors.AuthorModel author in edition.AuthorModels)//TODO redundant
                    {
                        <option>@author.Name</option>
                    }
                </select>
            </td>
            <td>@edition.Price</td>
            <td>@edition.Currency</td>
            <td>@edition.Status</td>
            <td>
                <input type="button" value="Profile" class="btn btn-default button" onclick="getProfile(@edition.Id);" />
                <input type="button" value="Delete" class="btn btn-default button" onclick="deleteEdition(@edition.Id);" />
            </td>
        </tr>
            }
        <tr>
            <td style="text-align:center;">
                SEARCH
            </td>
            <td>
                <input style="width: 98.3%" class="search" type="text" id="Title" />
                <script type="text/javascript">
                    document.getElementById("Title").value = JSON.parse(localStorage.getItem('editionTitleForSearch'));
                </script>
            </td>
            <td colspan="5">
                <input style="width: 100%" type="button" value="SEARCH" class="btn btn-default button" onclick="sort(`Id`,`asc`);" />
            </td>
        </tr>
        </table>
        <input style="width: 100%" type="button" value="ADD NEW EDITION" class="btn btn-default button" onclick="location.href='@Url.Action("AddNewEdition", "EditionManagement")'" />
        
        <div class="pagination">
            @if (@Model.PageModel.HasPreviousPage)
            {
                <input type="button" value="<<" class="btn btn-default button" onclick="navigateToPage(`1`);" />
                <input type="button" value="<" class="btn btn-default button" onclick="navigateToPage(`-1`);" />
            }

            @if (!@Model.PageModel.HasPreviousPage)
            {
                <input type="button" disabled="disabled" value="<<" class="btn btn-default button" />
                <input type="button" disabled="disabled" value="<" class="btn btn-default button" />
            }

            <input class="current-page" id="current" type="number" value="@Model.PageModel.PageNumber" min="1" step="1" onchange="navigateToPage();" />
            /@Model.PageModel.TotalPages

            @if (@Model.PageModel.HasNextPage)
            {
                <input type="button" value=">" class="btn btn-default button" onclick="navigateToPage(`+1`);" />
                <input type="button" value=">>" class="btn btn-default button" onclick="navigateToPage(@Model.PageModel.TotalPages);" />
            }

            @if (!@Model.PageModel.HasNextPage)
            {
                <input type="button" disabled="disabled" value=">" class="btn btn-default button" />
                <input type="button" disabled="disabled" value=">>" class="btn btn-default button" />
            }
        </div>
    </form>
}

@section scripts{
    <script>
        function sort(parametr, sortDirection)//TODO spelling
        {
            var editionTitleForSearch = document.getElementById("Title").value;
            var isAsc = sortDirection == "asc";

            localStorage.setItem("sortParametr", JSON.stringify(parametr));//TODO spelling
            localStorage.setItem("sortDirection", JSON.stringify(isAsc));

            localStorage.setItem("editionTitleForSearch", JSON.stringify(editionTitleForSearch));
            document.cookie = "editionTitleForSearch" + "=" + encodeURIComponent(editionTitleForSearch);

            return window.location.href = '@Url.Action("GetEditions", "EditionManagement")?sortBy=' + parametr + '&isAsc=' + isAsc;
        }

        function navigateToPage(page) {
            if (page === "+1" || page === "-1") {
                page = parseInt(document.getElementById("current").value) + parseInt(page);
            }
            if (page === undefined) {
                page = document.getElementById("current").value;
            }

            var sortParametr = JSON.parse(localStorage.getItem("sortParametr"));//TODO spelling
            var sortDirection = JSON.parse(localStorage.getItem("sortDirection"));
            if (!(sortParametr == "Id" || sortParametr == "Title" || sortParametr == "Price" || sortParametr == "Currency"
                || sortParametr == "Status")) {
                sortParametr = "Price";
            }
            return window.location.href = '@Url.Action("GetEditions", "EditionManagement")?sortBy=' + sortParametr + '&isAsc=' + sortDirection + '&page=' + page;
        }

        function getProfile(id) {
            return window.location.href = '@Url.Action("GetEditionProfile", "EditionManagement")?id=' + id;
        }

         function deleteEdition(id) {
            if(window.confirm("Do you really want to delete this edition?")){
            var currentURL = encodeURIComponent(window.location.href);
            return window.location.href = '@Url.Action("DeleteEdition", "EditionManagement")?id=' + id + '&url=' + currentURL;
            };
        }
        //TODO extra lines

    </script>
}

Store.PresentationLayer/Areas/Administration/Views/EditionManagement/UpdateEdition.cshtml
@model Store.BusinessLogicLayer.Models.EditionModel.EditionUpdateViewModel
@{
    Layout = "~/_Layout.cshtml";
}

@section AddToHead
{
    <link href="~/Styles/ManagementStyleSheet.css" rel="stylesheet" type="text/css" />
}
@{
    <div class=mainContent>
        <h2>Update edition</h2>
        <form class="stardart-font" asp-controller="EditionManagement" asp-action="UpdateEdition">
            <div class="form-group">
                <label asp-for="PrintingEdition.Id" class="control-label">Id</label>
                <input type="number" disabled="disabled" value="@Model.PrintingEdition.Id" />
                <input type="number" hidden="hidden" value="@Model.PrintingEdition.Id" asp-for="PrintingEdition.Id" />
            </div>

            <div class="form-group">
                <label asp-for="PrintingEdition.DateOfCreation" class="control-label">Created at</label>
                <input type="datetime" disabled="disabled" value="@Model.PrintingEdition.DateOfCreation" />
                <input type="datetime" hidden="hidden" value="@Model.PrintingEdition.DateOfCreation" asp-for="PrintingEdition.DateOfCreation" />
            </div>

            <div class="form-group">
                <label asp-for="PrintingEdition.Title" class="control-label">Title</label>
                <input type="text" value="@Model.PrintingEdition.Title" asp-for="PrintingEdition.Title" />
            </div>
            <div class="form-group">
                <label asp-for="PrintingEdition.Description" class="control-label">Description</label>
                <input type="text" value="@Model.PrintingEdition.Description" asp-for="PrintingEdition.Description" />
            </div>
            <div class="form-group">
                <label asp-for="PrintingEdition.EditionType" class="control-label">Edition Type</label>
                <select style="font-size: 16px" asp-for="PrintingEdition.EditionType">
                    <option selectedselected="selected">
                        @Model.PrintingEdition.EditionType
                    </option>
                    @if (@Model.PrintingEdition.EditionType.ToString() != "Book")
                    {
                        <option value="Book">Book</option>
                    }
                    @if (@Model.PrintingEdition.EditionType.ToString() != "Magazine")
                    {
                        <option value="Magazine">Magazine</option>
                    }
                    @if (@Model.PrintingEdition.EditionType.ToString() != "Newspaper")
                    {
                        <option value="Newspaper">Newspaper</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="NewAuthorsNames" class="control-label">Authors</label>
                <input id="newAuthors" hidden="hidden" type="text" value="" asp-for="NewAuthorsNames" />
                <input id="deletedAuthors" hidden="hidden" type="text" value="" asp-for="DeletedAuthorsNames" />
                <select style="font-size: 16px" id="authorForDel">
                    @foreach (Store.BusinessLogicLayer.Models.Authors.AuthorModel author in Model.PrintingEdition.AuthorModels)//TODO redundant
                    {
                        <option value="@author.Name">@author.Name</option>
                    }
                </select>
                <input type="button" value="Del Author" class="btn btn-default button" onclick="delAuthor();" />

                <select style="font-size: 16px" id="authorForAdd">
                    @foreach (Store.BusinessLogicLayer.Models.Authors.AuthorModel author in Model.AllAuthorModels)//TODO redundant
                    {
                        <option value="@author.Name">@author.Name</option>
                    }
                </select>
                <input type="button" value="Add author" class="btn btn-default button" onclick="addAuthor()" />
            </div>
            <div class="form-group">
                <label asp-for="PrintingEdition.Currency" class="control-label">Currency</label>
                <select style="font-size: 16px" asp-for="PrintingEdition.Currency">
                    <option selectedselected="selected">
                        @Model.PrintingEdition.Currency
                    </option>
                    @if (@Model.PrintingEdition.Currency.ToString() != "GBP")
                    {
                        <option value="GBP">GBP</option>
                    }
                    @if (@Model.PrintingEdition.Currency.ToString() != "USD")
                    {
                        <option value="USD">USD</option>
                    }
                    @if (@Model.PrintingEdition.Currency.ToString() != "EUR")
                    {
                        <option value="EUR">EUR</option>
                    }
                    @if (@Model.PrintingEdition.Currency.ToString() != "CHF")
                    {
                        <option value="CHF">CHF</option>
                    }
                    @if (@Model.PrintingEdition.Currency.ToString() != "JPY")
                    {
                        <option value="JPY">JPY</option>
                    }
                    @if (@Model.PrintingEdition.Currency.ToString() != "UAH")
                    {
                        <option value="UAH">UAH</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="PrintingEdition.Price" class="control-label">Price</label>
                <input type="text" value="@Model.PrintingEdition.Price" asp-for="PrintingEdition.Price" />
            </div>
            <div class="form-group">
                <label asp-for="PrintingEdition.Status" class="control-label">Status</label>
                <select style="font-size: 16px" asp-for="PrintingEdition.Status">
                    <option selected="selected" value="@Model.PrintingEdition.Status">@Model.PrintingEdition.Status</option>
                    @if (@Model.PrintingEdition.Status == "Available")//TODO spelling+++
                    {
                <option value="Unavaleble">Unavailable</option>//TODO spelling+++
                    }

                    @if (@Model.PrintingEdition.Status == "Unavailable")//TODO spelling+++
                    {
                <option value="Avaleble">Available</option>//TODO spelling+++
                    }
                </select>
            </div>
            <input type="submit" value="Update" class="btn btn-default button" />
        </form>
    </div>
}
@section scripts{
    <script>

        function addAuthor() {
            var authors = document.getElementById("newAuthors").value + ""

            if (authors === "") {
                document.getElementById("newAuthors").value = document.getElementById("authorForAdd").value;
                return;
            }

            var authorForAdd = document.getElementById("authorForAdd").value + "";

            if (!authors.includes(authorForAdd)) {
                document.getElementById("newAuthors").value = authors + ", " + authorForAdd;
            }
        }
        function delAuthor() {
            var authors = document.getElementById("deletedAuthors").value + ""

            if (authors === "") {
                document.getElementById("deletedAuthors").value = document.getElementById("authorForDel").value;
                return;
            }

            var authorForDel = document.getElementById("authorForDel").value + "";

            if (!authors.includes(authorForDel)) {
                document.getElementById("deletedAuthors").value = authors + ", " + authorForDel;
            }
        }
    </script>
}