Store.PresentationLayer/Areas/Administration/Controllers/OrdersManagementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Store.BusinessLogicLayer.Models.Orders;
using Store.BusinessLogicLayer.Serviсes.Interfaces;
using Store.Sharing.Constants;
using System.Threading.Tasks;

namespace Store.PresentationLayer.Areas.Administration.Controllers
{
    [Area("Administration")]
    public class OrdersManagementController : Controller
    {
        private readonly IOrderService _orderService;//TODO add new line
        public OrdersManagementController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> GetOrders(string sortBy = Constants.AreaConstants.ORDER_DEF_SORT_PARAMS, bool isAsc = true, int page = Constants.AreaConstants.FIRST_PAGE)
        {
            bool isUserId = long.TryParse(HttpContext.Request.Cookies[Constants.AreaConstants.USER_ID_COOKIES], out long userId);
            var sortModel = new OrderFiltrationModel
            {
                UserId = isUserId ? userId : null,
                PropertyForSort = sortBy,
                IsAscending = isAsc,
                CurrentPage = page,
                Description = HttpContext.Request.Cookies[Constants.AreaConstants.EDITION_DESC_COOKIES]//TODO wrong field
            };
            var result = await _orderService.GetAsync(sortModel);

            return View(Constants.AreaConstants.VIEW_ORDERS, result);

        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> GetOrder(long id)
        {
            var result = await _orderService.GetOrderDetails(id);

            return View(Constants.AreaConstants.VIEW_ORDER_PROFILE, result);

        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteOrder(long id)
        {
            await _orderService.RemoveAsync(id);
            var query = HttpContext.Request.Headers[Constants.AreaConstants.PATH].ToString();//TODO wrong spelling+++
            return Redirect(query);
        }
    }
}

Store.PresentationLayer/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Store.BusinessLogicLayer.Models.Orders;
using Store.BusinessLogicLayer.Serviсes.Interfaces;
using System.Threading.Tasks;

namespace Store.PresentationLayer.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class OrderController : Controller
    {
        private readonly IOrderService _orderServise;//TODO spelling

        public OrderController(IOrderService orderServise)//TODO spelling
        {
            _orderServise = orderServise;
        }
        //TODO extra line

        [HttpPost("GetById")]
        public async Task<IActionResult> GetById([FromBody] OrderModel model)
        {
            var result = await _orderServise.GetByIdAsync(model.Id);
            return Ok(result);
        }
 
        [HttpPost("Get")]
        public async Task<IActionResult> Get(OrderFiltrationModel model)
        {
            var result = await _orderServise.GetAsync(model);
            return Ok(result);
        }
    }
}

Store.PresentationLayer/Areas/Administration/Views/OrdersManagement/OrderProfile.cshtml
@model Store.BusinessLogicLayer.Models.Orders.OrderDetailsModel
@{
    Layout = "~/_Layout.cshtml";
}
@{
    <div style="margin-left: 40%">
        <h2>Order datails:</h2>/*//TODO spelling*/
        <a>Order Id:</a>
        <a class="from-query">@Model.OrderId</a><br>
        <a>Created at:</a>
        <a class="from-query">@Model.DateOfCreation</a><br>
        <a>User Id:</a>
        <a class="from-query">@Model.UserId</a><br>
        <a>User Name:</a>
        <a class="from-query">@Model.UserName</a><br>
        <a>Order items:</a>
        <ul>
            @foreach (Store.BusinessLogicLayer.Models.Orders.EditionInOrderDetails edition in Model.Editions)//TODO redundant,namespace, wrong field
            {
                <li>
                    Id:@edition.EditionId
                    <ul>
                        <li>Title: @edition.EditionTitle </li>
                        <li>Price: @edition.EditionPrice</li>
                        <li> Quantity: @edition.Count</li>                
                        <li>Total @edition.PriceForAllEditions</li>
                    </ul>
                </li>
            }
        </ul>
        <a>Final total:</a>
        <a class="from-query">@Model.TotalPrice</a><br>
        <a>Status</a>
        <a class="from-query">@Model.OrderStatus</a><br>
        @if (@Model.Description != null)
        {

            <a>Order Description:</a>
            <a class="from-query">@Model.Description</a><br>
        }
    </div>
}

Store.PresentationLayer/Areas/Administration/Views/OrdersManagement/Orders.cshtml
@model Store.BusinessLogicLayer.Models.PaginationsModels.NavigationModelBase<Store.BusinessLogicLayer.Models.Orders.OrderModel>
@{
    Layout = "~/_Layout.cshtml";
}

@section AddToHead
{
    <link href="~/Styles/ManagementStyleSheet.css" rel="stylesheet" type="text/css" />
}
@{


    <form id="ordersForm" class="stardart-font" asp-controller="OrdersManagement" asp-action="GetOrderes"> /*TODO check is action correct*/
        <table>
            <tr>
                <th>
                    Id
                    <span class="sort-button">
                        <input type="button" value="1-9" class="btn btn-default button" onclick="sort(`Id`,`asc`);" />
                        <input type="button" value="9-1" class="btn btn-default button" onclick="sort(`Id`,`dsc`);" />
                    </span>
                </th>
                <th>
                    Created at
                    <span class="sort-button">
                        <input type="button" value="1-9" class="btn btn-default button" onclick="sort(`DateOfCreation`,`asc`);" />
                        <input type="button" value="9-1" class="btn btn-default button" onclick="sort(`DateOfCreation`,`dsc`);" />
                    </span>
                </th>
                <th>
                    User Id
                    <span class="sort-button">
                        <input type="button" value="1-9" class="btn btn-default button" onclick="sort(`UserId`,`asc`);" />
                        <input type="button" value="9-1" class="btn btn-default button" onclick="sort(`UserId`,`dsc`);" />
                    </span>
                </th>
                <th>
                    Description
                </th>     
                <th>
                    Payment Id
                    <span class="sort-button">
                        <input type="button" value="1-9" class="btn btn-default button" onclick="sort(`PaymentId`,`asc`);" />
                        <input type="button" value="9-1" class="btn btn-default button" onclick="sort(`PaymentId`,`dsc`);" />
                    </span>
                </th>
                <th>
                    Order status
                    <span class="sort-button">
                        <input type="button" value="1-9" class="btn btn-default button" onclick="sort(`Status`,`asc`);" />
                        <input type="button" value="9-1" class="btn btn-default button" onclick="sort(`Status`,`dsc`);" />
                    </span>
                </th>

                <th>
                    Actions
                </th>
            </tr>
            @foreach (Store.BusinessLogicLayer.Models.Orders.OrderModel order in Model.Models)//TODO redundant, wrong field
            {
                <tr>
                    <td>@order.Id</td>
                    <td>@order.DateOfCreation</td>
                    <td>@order.UserId</td>
                    <td>@order.Description</td>
                    <td>@order.PaymentId</td>
                    <td>@order.Status</td>
                    <td>
                        <input type="button" value="Datails" class="btn btn-default button" onclick="getProfile(@order.Id);" />
                        <input type="button" value="Del" class="btn btn-default button" onclick="deleteOrder(@order.Id);" />
                    </td>
                </tr>
            }
            <tr>
                <td style="text-align:center;">
                    SEARCH
                </td>
                <td>
                    <input class="search" disabled="disabled" type="text" />
                </td>
                <td>
                    <input class="search" type="text" id="UserId" />
                    <script type="text/javascript">
                        document.getElementById("UserId").value = JSON.parse(localStorage.getItem('UserIdInOrder'));
                    </script>
                </td>
                <td>
                    <input class="search" type="text" id="Description" />
                    <script type="text/javascript">
                        document.getElementById("Description").value = JSON.parse(localStorage.getItem('descriptionForSearch'));
                    </script>
                </td>
                <td colspan="3">
                    <input style="width: 100%" type="button" value="SEARCH" class="btn btn-default button" onclick="sort(`Id`,`asc`);" />
                </td>
            </tr>
        </table>
        <div class="pagination">
            @if (@Model.PageModel.HasPreviousPage)
            {
                <input type="button" value="<<" class="btn btn-default button" onclick="navigateToPage(`1`);" />
                <input type="button" value="<" class="btn btn-default button" onclick="navigateToPage(`-1`);" />
            }

            @if (!@Model.PageModel.HasPreviousPage)
            {
                <input type="button" disabled="disabled" value="<<" class="btn btn-default button" />
                <input type="button" disabled="disabled" value="<" class="btn btn-default button" />
            }

            <input class="current-page" id="current" type="number" value="@Model.PageModel.PageNumber" min="1" step="1" onchange="navigateToPage();" />
            /@Model.PageModel.TotalPages

            @if (@Model.PageModel.HasNextPage)
            {
                <input type="button" value=">" class="btn btn-default button" onclick="navigateToPage(`+1`);" />
                <input type="button" value=">>" class="btn btn-default button" onclick="navigateToPage(@Model.PageModel.TotalPages);" />
            }

            @if (!@Model.PageModel.HasNextPage)
            {
                <input type="button" disabled="disabled" value=">" class="btn btn-default button" />
                <input type="button" disabled="disabled" value=">>" class="btn btn-default button" />
            }
        </div>
    </form>
}
@section scripts{
    <script>
        function sort(parametr, sortDirection)//TODO spelling
        {
            var userIdForSearch = document.getElementById("UserId").value;
            var descriptionForSearch = document.getElementById("Description").value;

            var isAsc = sortDirection == "asc";

            localStorage.setItem("sortParametr", JSON.stringify(parametr));//TODO spelling
            localStorage.setItem("sortDirection", JSON.stringify(isAsc));

            localStorage.setItem("UserIdInOrder", JSON.stringify(userIdForSearch));
            document.cookie = "UserIdInOrder" + "=" + encodeURIComponent(userIdForSearch);

            localStorage.setItem("descriptionForSearch", JSON.stringify(descriptionForSearch));
            document.cookie = "descriptionForSearch" + "=" + encodeURIComponent(descriptionForSearch);

            return window.location.href = '@Url.Action("GetOrders", "OrdersManagement")?sortBy=' + parametr + '&isAsc=' + isAsc;
        }

        function navigateToPage(page) {
            if (page === "+1" || page === "-1") {
                page = parseInt(document.getElementById("current").value) + parseInt(page);
            }
            if (page === undefined) {
                page = document.getElementById("current").value;
            }

            var sortParametr = JSON.parse(localStorage.getItem("sortParametr"));//TODO spelling
            var sortDirection = JSON.parse(localStorage.getItem("sortDirection"));
            if (!(sortParametr == "Id" || sortParametr == "DateOfCreation" || sortParametr == "UserId" || sortParametr == "PaymentId"
                || sortParametr == "Status")) {
                sortParametr = "Id";
            }
            return window.location.href = '@Url.Action("GetOrders", "OrdersManagement")?sortBy=' + sortParametr + '&isAsc=' + sortDirection + '&page=' + page;
        }

        function getProfile(id) {
            return window.location.href = '@Url.Action("GetOrder", "OrdersManagement")?id=' + id;

        } function deleteOrder(id) {
            if(window.confirm("Do you really want to delete this order?")){
            return window.location.href = '@Url.Action("DeleteOrder", "OrdersManagement")?id=' + id;
            };
        }
        //TODO extra lines

    </script>
}